name: Sugarcanetracker
version: ${project.version}
main: me.darkeyedragon.sugarcanetracker.Sugarcanetracker
author: KrypticOP
commands:
  sugarcanestats:
    description: Show the sugarcane leaderboard
    usage: /st <stats/reload>
    aliases: [sugarcanetracker, st, sugartracker, sugarstats]
